name: Build & Test CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: yarn build
      - name: Automated tests
        run: yarn test
      - name: Visual regression tests
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn test:chromatic